
services:
  app:
    image: ${DOCKERHUB_USERNAME}/camchelin
    build: .
    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      REGION: ${REGION}

      hibernate_ddl_auto: update
#      REDIS_HOST: redis
#    depends_on:
#      - redis

#  redis:
#    image: "redis:latest"
#    ports:
#      - "6379:6379"
