spring:
  application:
    name: camchelin

  datasource:
    url: jdbc:mysql://localhost/camchelin # rds_endpoint
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

      #url: ${DB_URL}
      #username: ${DB_USERNAME}
      #password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    include: jwt

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 10000
    header: Authorization
  refresh:
    expiration: 90
    header: Authorization-refresh
