spring:
  application:
    name: camchelin

  datasource:
    url: jdbc:mysql://localhost/camchelin # rds_endpoint
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

      #url: ${DB_URL}
      #username: ${DB_USERNAME}
      #password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    include: jwt

  data:
    redis:
      host: localhost       # Redis 서버 호스트 (기본값 localhost)
      port: 6379            # Redis 서버 포트 (기본값 6379)
      password:   # 비밀번호 설정 (설정된 경우)

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 1800  #30분
    header: Authorization
  refresh:
    expiration: 18000 #300분
    header: Refresh


