name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Repository의 코드를 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Java 17 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle로 JAR 파일 빌드 (테스트 제외)
      - name: Build JAR file
        run: ./gradlew clean build -x test

      # 4. DockerHub에 로그인
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t tjdgus3488/camchelin:latest . --push

      # 6. EC2에 SSH로 접속 및 컨테이너 실행
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull tjdgus3488/camchelin:latest
            docker stop camchelin|| true
            docker rm camchelin || true
            docker run -d --name camchelin -p 8080:8080 tjdgus3488/camchelin:latest
